### ISSUE TITLE
Distributed sampling doesn't work right for weighted sampling or nested probabilistic properties

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hlsyounes/ymer#19]
```
Two issues:

1) The sample weight isn't sent from client to server.
2) The nested error isn't sent from server to client. 
```

Original issue reported on code.google.com by `hlsyou...@gmail.com` on 14 Mar 2015 at 10:36

**Comment by hlsyounes** [comment]
Obsolete with implementation of mutli-threaded sampling in [4816290](https://github.com/hlsyounes/ymer/commit/48162905680a413c9df25d6c0b2ab60015739758), which replaces the old distributed sampling implementation.
